---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgADX8KrtGg/XiQppVEYEif9BxGkt0b1Qn9nVw0etKOV5/hA5Iw5MO/D602VPCmT+LLcN6BiY4TLxy6HU2CstKQQ+OUWfOAF0DUmCGkLuaTDlML/S7HuS36z7WcEPI1l8nJVfcXAxkuEvhZdt0GsdnVYcyu7n5FyxhDcl3cmCKOVb6xExf+D9lxr6UbiAAJBWM2gEpkssvqQhf/sip6XpI8okSrcbavXD8BE28r4Cl8fTP8vrlgVYFFNvl7HkGG4XLDZQshPOKwVBLAWq0kEluUJQaCdZSp2MTO7Fz3dN5VLdHGp85hZICim4k5YsFDCSCaXkQ2uHQ2W6mzU7eRGlYzD4q8UFDrtUfWYPRX5ZqAfE5u2IqEccy3+Ewbv0LHtD0f5tguYcvhB1g3X2myBU7xm5TzK5geQ/AqmnoRYdapWqBMSpyobAioHKKxUvhSmHu39QYaCe6VL0Mb0XtpD0vRwoREXEPqTjd15vUtaaVGE6e3mIpEMeTXoWNbFSsrxMnf2dO69Cq/t/ZsJF151gS1lTuiJR5BmPy+c0Yl7As/Y9eLOIHfEQ78+8NrCvHlxjw9emfu77w1FKBBz8PjK6nGpoAL4noCem1RdAB5If4i3uhGrfUM232C0LRe6EeTMqUWNdpYA6yuFVj03iPyomOQkyCCRBiwxKkiKjrulywIra1ByELPQwadtNO7loYL6CBD5VXA7btza6sqaPEAGxAk=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
