---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgAwj7AEFuYf1M6Jv74TpRYB85u7hsI2080wmQUKRosqZ1d5L978uVGECyvQ0vS/Im0+40CfoEzSpkJ6SR7YNcKbD1wUn2QZKFeUAgACweNNzq+B6rlnSQa0CqODDvsIT9pVWOajL3CM+flKEktPOiQQdXqldxFZ+s3jLFSLekPW5XesViJZE4LVSbqAmQlPzNcB52DBSJv6LVNFh68+7LC2flKGY0cGe/MrrYKtWzPCO6SVHu8zoMaZLvntynlo2bxuHuKY6B1DaK8oGaP1j046TXBtbjNI4WjElA1FylofHdSyzeUGEQcDTiHWZ/q6SZEIbSiUR0vF13nFI1/m9UFft6noBV/KcWc0cEHqC2DbyjrFsZ8KxbpIsVmXhkVKWVOhg/RNGxvgwyjesL2Ghx3jQyB7hXkgzg6VxuIPYPIB6oIXMgM13JSTDMTswAybPNcZBrdsD74vhqMI1bhAXtXyL7Tpwn1Mh9+Fgc782UfU27iDfOxIpz7fsWCYBs43+SPL/rUZmka/64M4OATIPFTX3tsj1Nxpcy++9ehFdD0CRNyEmYLbDhSszwyzmI8SVEVi82oHnk1yAV0OZ4Qd39IGou8uuLoogGb3CEZjFRxMh/AZz8wV7GdhGoPJGcjl949VTjr0B6YdOdE7TG4QKWWYdjHmnwDDKl+70lCR39DTC+3152GFt4E3lbizFiZ/S2A80OOYG8TZzOlVqwDibwSx8U/e
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
