---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgCRGBBkYM6dVCjKH4y/jaImVh3CvEks/meEEHbqiqepW8YTjxeDT7Fe855WzEEtCImAP4G4/iMHsozcHmfnGOH7vfFoyFBwvnfd6exgi55N3uyXjPlippDgI/VU87kRDMBw+UF98O+ig5gRvYsrwybYQ2xJ5NDde11B3bbEiKA8WbAgNMyTTy0umMArhGKCxstkCb9HnqK9SeXqFWUKxRB/I/VYS2vH3HQhZgnQjPBoaapfSf0a9SLpX7FgIhi9A3HPKkxxQ4hduXkTnEnsnqD4m0M62S/HtvTAt+LrhpRyL91keG5oXnV7uQ+0Tyfm+bpYql9sLElHH6iPAQerk9pctgjGHQOULlgOnNAe3w5T1XWNvsYRAh63saHmRYFHk39hJw+1Od7WJA5wXpU0194TIK+FFgJOmOX/K5Ki4tRD7SDkwal0hAuYzDQKMIrEexV9XqbhXsnhRS9Y4Weadu0MIpg5b6ZYwMK9NgWKY9UGG9+MfdNkZw/C/i9gNoXmB6T7x5fzTP92zXjJA8miZ57ibt5BanoYlrYv+GsZqs/vtLSbxjVC9/+F1WQjltFDY4n+Fq2Tc9jfgXYvohfv+J3Z0q/ZjEq/BwMiyp1Zpw2FJbCPX5HmwXIRw8H4kP9b0w5myAnM3KOzPFeSYFVUAdUucrvx4rnuHejr9+2iByfMuXvEjoxFwTSnbZRVIaGPObEVhy+wSts5NJwFpoRM
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
