---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgBMJ07ytwx53UMiD0pqzRwXsr+h4MGBSv2imYOde+ZlMFERnQdZ0e0E715JpgqpVIY5olzfQbmMg/wohWFwQMyjWBewse+Yd2WgTDJJh5HN9zHfTG6BrnlaeYMiHPhpfM2zbFXULkduPtcPlzlqUWuSvz2mOpDEgcMQqwSS+rDS7HubNyBlsNE3wxdMi/TGAKyJVDepyGYU1YhJNVNeGWYKJt6BdMqJyU+/eiZC7ANIRfJa1JaA/fXYSwsiejyqPVA216m57Rj/rmv+O7fxh+wNO7sMQCMgQ5Syn6CsScxQjwiOTpyKPDXzpoK4AQ2lEXPmMtw4CoV/OkKHkTq8bAL70Bw28zbKUv1Y1HURGpLfmZc7gnbluxpSxfHRniY4jw3/W4+4eT4s88p7J9Ojclnc/VHlCex4tOSjDt+3hNTd4ZB/BFkJRUI8xN0dgG+Xh7EqLckS93Kn1BrhT/jYSAl5UYPvepvYU4j00OtZ0C/d2L30NmMj6z7+OOoe3TLMfhY6eSo7hoT1vRVtxfQjFHA974rJwRLnYhFVPYP2vWcnECTeX7sWSU3HI9AG67/i9580cSzzQWR4yQq4o7478302v3la6620bo8NzKih4E3uqDyDh/Oiqzsr9PDDA2hdBIIk0QgI7ewkWcLzk5/+EJQygfx8vOxbzvSoOlemMKa40Xs4O0GgWSJvjcW86AR9bXtoeMR+nmdU8zsIe6bcpIE=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
