---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgB73mYBs0ZxqofpiT6jo8C1Z5g26fue9zmmLMdxz1n9s+MDW3JbYZvpBA7E/Zva8SOnfW2oLrAf3ymajUdYr1dGpNBcy+u3AxSBWfbNzXld8UtlCqEhynVmQ0tj6mcg+Z+NnoE8EJGsYt+QlVQLPL1R8eXyoYxnOQfU5cXGzuUuqaNjYh11yUD7HFIWfRx1PGRplOth1SbO/sSQ/ubbHIaqOZAmxw7MUkGtUBNnhf5M+9MzP2S7UEuhiOX6EdtiuiTwJL56Au8c9uO65DTpMwQpVSEOnfhYLZEYHStoKtmzcE6jsIF0Q3BDMtLCAFEX4oPMNqmp9YTGNVZrvXFg+jW+WlmnN/R+8WMpqvQ+SAu92VgUYOY//LxiBBiTQqIY/484mPB02lK/YVyMEz+ttXVA/GMK5sNVjSuw40IaXj/tcwpuK0/25SSXTTu6BLG8HYAcouvzwOu/UjYI7CS5r1nvdcOyIbsATvCg1RysYhKRGjxRea9EUbcXlbWZTT6aQRvFyBwd4pB3PbuoZGAyrgDWC0s0BsDnwspL+9b5V4ADqx1GNa+JUhqzPt+ZJ5odHR7kkKdAGvUQmVUxxA/9FK1IX6M2PbvHvicZNN0wkVUABZ5vyjGqy7qhlZuXzJrpBDOXZUgBhJTB/5va/035FTLUuF+fnzHj9wyoLMv+FIqJ5nTvxl30kZKqj1gPHxSiiTKcVPQVB5tv/QKFdsidUEEc
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
